/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class ThicketIdeaModule extends AbstractThicketIdeaModule {
}
