/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class ThicketIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new ThicketStandaloneSetupIdea().createInjector
	}

}
