/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class ThicketLanguage extends AbstractXtextLanguage{

	public static final ThicketLanguage INSTANCE = new ThicketLanguage();

	private ThicketLanguage() {
		super("org.thicket.lang.xtext.Thicket");
	}

}
