/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.thicket.lang.xtext.thicketDSL.Model

@RunWith(XtextRunner)
@InjectWith(ThicketInjectorProvider)
class ThicketParsingTest{

	@Inject
	ParseHelper<Model> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
