/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.lang


class ThicketFileType extends AbstractThicketFileType {
	public static final ThicketFileType INSTANCE = new ThicketFileType()
	
	new() {
		super(ThicketLanguage.INSTANCE)
	}
}
