/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractThicketCompletionContributor extends TerminalsCompletionContributor {
	public AbstractThicketCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
