/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.scoping

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ThicketScopeProvider extends AbstractDeclarativeScopeProvider {

}
