/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ThicketStandaloneSetup extends ThicketStandaloneSetupGenerated {

	def static void doSetup() {
		new ThicketStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
