/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ThicketRuntimeModule extends AbstractThicketRuntimeModule {
}
