/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.lang.parser;

import com.google.inject.Inject;
import com.intellij.lang.PsiBuilder;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.antlr.runtime.TokenStream;
import org.eclipse.xtext.idea.parser.AbstractPsiAntlrParser;
import org.eclipse.xtext.idea.parser.AbstractXtextPsiParser;
import org.thicket.lang.xtext.idea.lang.ThicketElementTypeProvider;
import org.thicket.lang.xtext.idea.parser.antlr.internal.PsiInternalThicketParser;
import org.thicket.lang.xtext.services.ThicketGrammarAccess;

public class ThicketPsiParser extends AbstractXtextPsiParser {
	private static final Set<String> INITIAL_HIDDEN_TOKENS = new HashSet<String>(Arrays.asList("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT"));
	
	@Inject 
	private ThicketGrammarAccess grammarAccess;

	@Inject 
	private ThicketElementTypeProvider elementTypeProvider;

	@Override
	protected AbstractPsiAntlrParser createParser(PsiBuilder builder, TokenStream tokenStream) {
		return new PsiInternalThicketParser(builder, tokenStream, elementTypeProvider, grammarAccess);
	}
	@Override
	protected Set<String> getInitialHiddenTokens() {
		return INITIAL_HIDDEN_TOKENS;
	}
}
