/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.thicket.lang.xtext.idea.lang.ThicketLanguage;

public class ThicketPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {
	public ThicketPomDeclarationSearcher() {
		super(ThicketLanguage.INSTANCE);
	}
}
