/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor class ThicketWebModule extends AbstractThicketWebModule {
}
