/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.thicket.lang.xtext.idea.lang.ThicketLanguage

class ThicketCompletionContributor extends AbstractThicketCompletionContributor {
	new() {
		this(ThicketLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
