/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.thicket.lang.xtext.services.ThicketGrammarAccess
import org.eclipse.xtext.formatting2.IFormattableDocument

class ThicketFormatter extends AbstractFormatter2 {
	
	@Inject extension ThicketGrammarAccess

	override format(Object obj, IFormattableDocument document) {
		throw new UnsupportedOperationException()
	}

}
