/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import org.thicket.lang.xtext.idea.lang.ThicketLanguage;

public class ThicketSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public ThicketSemanticHighlightVisitor() {
		ThicketLanguage.INSTANCE.injectMembers(this);
	}
}
