/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.jetbrains.annotations.NotNull;
import org.thicket.lang.xtext.idea.lang.ThicketLanguage;

public class ThicketSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
    @NotNull
    protected SyntaxHighlighter createHighlighter() {
        return ThicketLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
    }
}
