/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.thicket.lang.xtext.idea.lang.ThicketLanguage;

public class ThicketFacetType extends AbstractFacetType<ThicketFacetConfiguration> {

	public static final FacetTypeId<Facet<ThicketFacetConfiguration>> TYPEID = new FacetTypeId<Facet<ThicketFacetConfiguration>>("org.thicket.lang.xtext.Thicket");

	public ThicketFacetType() {
		super(TYPEID, "org.thicket.lang.xtext.Thicket", "Thicket");
		ThicketLanguage.INSTANCE.injectMembers(this);
	}
}
