/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.thicket.lang.xtext.idea.lang.ThicketLanguage;

public class ThicketExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return ThicketLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
