/*
 * generated by Xtext 2.9.0.beta5
 */
package org.thicket.lang.xtext.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;
import org.thicket.lang.xtext.ide.contentassist.antlr.ThicketParser;
import org.thicket.lang.xtext.ide.contentassist.antlr.internal.InternalThicketLexer;

/**
 * Manual modifications go to {@link ThicketWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractThicketWebModule extends DefaultWebModule {

	public AbstractThicketWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalThicketLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return ThicketParser.class;
	}
	
}
